[tool.poetry]
name = "content-manager"
dynamic = ["version"]
description = "Gestionnaire de contenu permettant de créer et gérer un site internet basé sur le Système de design de l'État, accessible et responsive"
authors = [
  {name = "Sébastien Reuiller", email = "sebastien.reuiller@beta.gouv.fr"},
  {name = "Sylvain Boissel", email = "sylvain@boissel.dev"},
]
maintainers = [
  {name = "Sylvain Boissel", email = "sylvain@boissel.dev"}
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.7"
wagtail = "^5.2.1"
django-dsfr = "^0.16.2"
psycopg2-binary = "^2.9.9"
python-dotenv = "^1.0.0"
dj-database-url = "^2.1.0"
gunicorn = "^21.2.0"
django-sass-processor = "^1.3"
libsass = "^0.22.0"
dj-static = "^0.0.6"
wagtailmenus = "^3.1.9"
boto3 = "^1.29.1"
django-storages = "^1.14.2"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
pre-commit = "^3.5.0"
djlint = "^1.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 119
